//对外暴露配置路由
export const constantRoute = [
        {
            //登录
            path:'/login',
            component:()=>import('@/views/login/index.vue'),
            name:'login',//命名路由,做权限时需要用name区分
        },
        {
            //登录成功后展示数据
            path:'/',
            component:()=>import('@/layout/index.vue'),
            name:'layout'//名字随意
        },
        {
            //404
            path:'/404',
            component:()=>import('@/views/404/index.vue'),
            name:'notFound'
        },
        {
            //任意路径，不能匹配则跳404
            path:'/:patchMatch(.*)*',
            redirect:'/404',
            name:'Any'
        }
    ]
